There must only be one graphql version installed
Otherwise:

  ✔ Loading Apollo Project
  ✖ Saving schema to external/graphql/schema.json
    → spurious results.
    Error: Cannot use GraphQLSchema "{ __validationErrors: undefined, description: undefined, extensions: undefined, astNode: undefined, extensionASTNodes: undefined, _queryType: Query, _mutationType:
    Mutation, _subscriptionType: null, _directives: [@include, @skip, @deprecated], _typeMap: { AuthProviderCredentialsInput: AuthProviderCredentialsInput, Boolean: Boolean, CreateSupportTicketPayload:
     CreateSupportTicketPayload, CreateSurveyQuestionResponsePayload: CreateSurveyQuestionResponsePayload, CreateSurveyResponsePayload: CreateSurveyResponsePayload, ID: ID, ISO8601DateTime:
    ISO8601DateTime, Int: Int, MeetingDuration: MeetingDuration, Mutation: Mutation, Query: Query, Question: Question, QuestionOption: QuestionOption, SignInUserPayload: SignInUserPayload, String:
    String, Student: Student, SupportTicket: SupportTicket, Survey: Survey, SurveyQuestionResponse: SurveyQuestionResponse, SurveyResponse: SurveyResponse, UpdateUserInput: UpdateUserInput, User: User,
     __Directive: __Directive, __DirectiveLocation: __DirectiveLocation, __EnumValue: __EnumValue, __Field: __Field, __InputValue: __InputValue, __Schema: __Schema, __Type: __Type, __TypeKind:
    __TypeKind }, _subTypeMap: {}, _implementationsMap: {} }" from another module or realm.

    Ensure that there is only one instance of "graphql" in the node_modules
    directory. If different versions of "graphql" are the dependencies of other
    relied on modules, use "resolutions" to ensure only one version is installed.

    https://yarnpkg.com/en/docs/selective-version-resolutions

    Duplicate "graphql" modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.
.../src/graphql/mutations/CreateSupportTicket.ts: Cannot query field "createSupportTicket" on type "Mutation".
.../src/graphql/mutations/UpdateUserMutation.ts: Cannot query field "updateUserPassword" on type "Mutation". Did you mean "updateUser"?
Validation of GraphQL query document failed
    at Object.validateQueryDocument (/Users/garettarrowood/Development/inkind-volunteer/node_modules/apollo-language-server/lib/errors/validation.js:40:38)
    at Object.generate [as default] (/Users/garettarrowood/Development/inkind-volunteer/node_modules/apollo/lib/generate.js:23:18)
    at write (/Users/garettarrowood/Development/inkind-volunteer/node_modules/apollo/lib/commands/client/codegen.js:83:54)
    at Task.task (/Users/garettarrowood/Development/inkind-volunteer/node_modules/apollo/lib/commands/client/codegen.js:103:46)
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → spurious results.
    Error: Cannot use GraphQLScalarType "ID" from another module or realm.

    Ensure that there is only one instance of "graphql" in the node_modules
    directory. If different versions of "graphql" are the dependencies of other
    relied on modules, use "resolutions" to ensure only one version is installed.

    https://yarnpkg.com/en/docs/selective-version-resolutions

    Duplicate "graphql" modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.